### ISSUE TITLE
File capabilities getting lost

### ISSUE THREAD

**Issue by ebfe** [scaleway/image-archlinux#16]
It seems that somewhere in the image build process file capabilities get dropped for `ping` (and potentially other files with file capabilities set).

    $ scw create --name arch Archlinux
    <server-id>
    $ scw exec arch bash
    [root@arch ~]# useradd -m dummy
    [root@arch ~]# su dummy
    [dummy@arch root]$ ping scaleway.com
    ping: icmp open socket: Operation not permitted
    [root@arch ~]# getcap /bin/ping

Reinstalling the iputils package fixes this:

    [root@arch ~]# pacman -S iputils
    warning: iputils-20140519.fad11dc-1 is up to date -- reinstalling
    resolving dependencies...
    ...
    (1/1) reinstalling iputils                                                                                                              [###################################################################################] 100%
    [root@arch ~]# su dummy
    [dummy@arch root]$ ping scaleway.com
    PING scaleway.com (212.47.225.64) 56(84) bytes of data.
    64 bytes from 64-225-47-212.int.cloud.online.net (212.47.225.64): icmp_seq=1 ttl=60 time=0.229 ms
    64 bytes from 64-225-47-212.int.cloud.online.net (212.47.225.64): icmp_seq=2 ttl=60 time=0.216 ms
    ^C
    --- scaleway.com ping statistics ---
    2 packets transmitted, 2 received, 0% packet loss, time 999ms
    rtt min/avg/max/mdev = 0.216/0.222/0.229/0.016 ms
    [dummy@arch root]$ exit
    [root@arch ~]# getcap /bin/ping
    /bin/ping = cap_net_raw+ep

**Comment by ebfe** [comment]
Affected files in the base image:

    # iputils
    /usr/bin/ping
    /usr/bin/ping6
    # inetutils
    /usr/bin/rcp
    /usr/bin/rlogin
    /usr/bin/rsh

**Comment by moul** [comment]
I think this is due to the way we are exporting the image as a Tarball file, we will try to preserve advanced capabilities while exporting image, else we will add a file that will change capabilities on first run, thanks for reporting

**Comment by moul** [comment]
I'm closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue.

Thank you!
