### ISSUE TITLE
docker does not work

### ISSUE THREAD

**Issue by inigoserna** [scaleway/image-archlinux#21]
Docker daemon execution fails with this error:
```
WARN[0000] You are running linux kernel version 3.2.34-30, which might be unstable running docker. Please upgrade your kernel to 3.10.0. 
DEBU[0000] devicemapper: driver version is 4.22.0       
DEBU[0000] Generated prefix: docker-43:0-1441816        
DEBU[0000] Checking for existence of the pool 'docker-43:0-1441816-pool' 
DEBU[0000] Pool doesn't exist. Creating it.             
ERRO[0000] [graphdriver] prior storage driver "devicemapper" failed: Error running DeviceCreate (CreatePool) dm_task_run failed 
FATA[0000] Error starting daemon: error initializing graphdriver: Error running DeviceCreate (CreatePool) dm_task_run failed 
```

It looks like docker v1.7.1 needs a newer linux kernel.
Last debian:8 image works, but that has a linux kernel v4.1.x.

**Comment by moul** [comment]
@inigoserna you can change your current bootscript to get a more recent kernel, I suggest you to pick up the Docker one which is recent enough and contains some specific addons for Docker

See: https://www.scaleway.com/docs/bootscript-and-how-to-use-it/

For your information, the next version of the image will be built with a more recent kernel by default

**Comment by inigoserna** [comment]
OK, I've just learned what bootscripts are. Tested and working with v4.2. 
Thanks!

**Comment by moul** [comment]
:)

**Comment by inigoserna** [comment]
I've tested with '4.2-docker #253' and '4.1.6-apparmor #247' boot scripts, docker daemon starts but it fails when running a container:
```
[root@test01 ~]# docker run -ti --rm armbuild/alpine sh
Error response from daemon: Cannot start container 4185d6e3069887c59262b451ef59fd868c8d6e85bc28e8b59aabbb6198f29701: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/init.scope/system.slice/docker-4185d6e3069887c59262b451ef59fd868c8d6e85bc28e8b59aabbb6198f29701.scope/cpu.shares: no such file or directory
```

The problem comes from the upgrade of systemd to version 226-3. One possible fix is to downgrade all systemd packages to v225.
But a better solution is to add `--exec-opt native.cgroupdriver=cgroupfs` to the file '/usr/lib/systemd/system/docker.service'.

More info:
- http://archlinuxarm.org/forum/viewtopic.php?t=9337&p=48702
- https://github.com/docker/docker/issues/16256

**Comment by moul** [comment]
@inigoserna thanks for the investigation

We concentrate our efforts on image using Ubuntu: https://github.com/scaleway-community/scaleway-docker

If you want to improve the Docker support on Archlinux, feel free to open a pull request here

If you need specific tweaks on the kernel-side, you can create new issue here: https://github.com/scaleway/kernel-tools so we can fix it for you

**Comment by inigoserna** [comment]
It is an ArchLinux issue, some untested changes in a new version of systemd that had some bad hidden effects in docker.
I don't like Ubuntu, sorry. Anyway, I'm a hobbyist so I'm pretty satisfied with the level of support you are providing to non official images. Thanks a lot, by the way.

**Comment by moul** [comment]
Ok, perfect, do not hesitate to speak here about issues etc, maybe we can help, else it can help other archlinux fans to solve similar issues
