### ISSUE TITLE
Can't SSH after upgrade with "pacman -Syu"

### ISSUE THREAD

**Issue by vikbez** [scaleway/image-archlinux#25]
steps to reproduce:

- Create a new server from the arch image
- SSH to it, run `pacman -Syu`
- reboot it
- try to SSH to it again

boot seems normal:
```
[  OK  ] Reached target Basic System.                                                                                                                                          
         Starting SSH Key Generation...                                                                                                                                        
[  OK  ] Started Entropy Harvesting Daemon.                                                                                                                                    
         Starting Network Name Resolution...                                                                                                                                   
         Starting SCW fetch ssh keys from metadata...                                                                                                                          
         Starting SCW fetch kernel modules from Scaleway mirror...                                                                                                             
         Starting Permit User Sessions...                                                                                                                                      
         Starting SCW generate ssh keys on first boot...                                                                                                                       
[  OK  ] Started Daily man-db cache update.                                                                                                                                    
[  OK  ] Reached target Timers.                                                                                                                                                
[  OK  ] Started D-Bus System Message Bus.                                                                                                                                     
         Starting Network Service...                                                                                                                                           
         Starting Login Service...                                                                                                                                             
[  OK  ] Started Network Name Resolution.                                                                                                                                      
[  OK  ] Started SSH Key Generation.                                                                                                                                           
[  OK  ] Started SCW fetch kernel modules from Scaleway mirror.                                                                                                                
[  OK  ] Started Permit User Sessions.                                                                                                                                         
[  OK  ] Found device /dev/ttyS0.                                                                                                                                              
[  OK  ] Started Network Service.                                                                                                                                              
[  OK  ] Reached target Network.                                                                                                                                               
         Starting One-Shot Network Time Service...                                                                                                                             
[  OK  ] Started Serial Getty on ttyS0.                                                                                                                                        
[  OK  ] Reached target Login Prompts.                                                                                                                                         
         Starting SCW generate machine id...                                                                                                                                   
[  OK  ] Started Login Service.                                                                                                                                   
```

**Comment by moul** [comment]
ping @aimxhaisse, do you have a clue ?

**Comment by mikkeloscar** [comment]
Hello, I submitted the ticket about this, and I noticed when I ran an update and got systemd 228 and then rebooted. So i suspect it could have something to do with updating from systemd 227 to 228.

**Comment by cocoto** [comment]
I also think that *systemd 228* is the guilty.
I mounted my partition in an other server (/dev/nbd1), downloaded **systemd 226 in [this repo](http://fraggod.net/static/mirror/packages/archlinuxarm/armv7h/)** and installed with `pacman -r myMountedFolder -U systemd-226-3.1-armv7h.pkg.tar.xz`

The server works again and boot well
I hope that it can help you

**Comment by mikkeloscar** [comment]
I can confirm that this indeed is caused by the `systemd 228` update. If you spawn a new instance and update anything but `systemd, systemd-sysvcompat, libsystemd` then the instance will continue to work after a reboot.

**Comment by manchoz** [comment]
Alternate rescue method using Rescue bootscript and ```chroot```. (***No need to detach volume***)

- Go to the server management panel e choose "Rescue" as bootscript (Unhide ADVANCED options).
- Do an Hard Reboot.
- Connect via ```ssh``` to the server's public IP address with ```root``` user.
- Mount the volume
```
# mount /dev/nbd0 /mnt
```
- Setup the ```chroot``` environment
```
# cd /mnt
# mount -t proc proc proc/
# mount --rbind /sys sys/
# mount --rbind /dev dev/
# mount --rbind /run run/
# cp /etc/resolv.conf etc/resolv.conf
```
- Chroot
```
# chroot /mnt/arch /bin/bash
```
- Downgrade to previous systemd-227-1. (Assuming having previous ```systemd``` packages still in ```pacman``` cache. YMMV).
```
pacman -U /var/cache/pacman/pkg/systemd-227-1-armv7h.pkg.tar.xz
```
- Exit chroot
```
CTRL-D
```
- Go to server managment panel and select back the default bootscript ```4.1.6-std #249```
- Reboot from shell or Hard reboot from panel
- Voila!

*PS*
- To prevent systemd from being upgraded at next ```pacman -Syu``` add ```IgnorePkg=systemd``` to ```/etc/pacman.conf```

**Comment by QuentinPerez** [comment]
Thanks a lot for your instructions @manchoz 😊👍🏻

**Comment by manchoz** [comment]
You welcome, @QuentinPerez!

**Comment by pavlos256** [comment]
Thanks everyone and @manchoz for the easy fix. Has this been reported upstream?

**Comment by mikkeloscar** [comment]
@pavlos256 what do you mean by upstream? I have made a ticket with scaleway who in turn has created this issue.

@manchoz I think you might want to use: `IgnorePkg=systemd libsystemd systemd-sysvcompat` to keep them all at the same version.

**Comment by pavlos256** [comment]
@mikkeloscar By upstream I meant Arch Linux ARM or systemd. Or is this problem specific to Scaleway?

**Comment by manchoz** [comment]
@pavlos256 I think that the problem is specific to Scaleway since I have several armv7 Arch Linux machines (RPis, BBBs, CB2, etc) which run systemd-228 whitout any issue.

My guess is that the problem is related to networking/DHCP: the system hangs/become unreachable also whan a ```systemctl restart systemd-networkd``` is executed (only with systemd-228).

**Comment by pavlos256** [comment]
I applied patch 122793e to my server and I was able to boot with systemd 228.

**Comment by jezze** [comment]
Pavlos256 patch worked for me. Basically what I did was:

1. Select the Rescue script in the control panel
2. Reboot machine
3. Login as root
4. Mount /dev/nbd0 to /mnt
5. Edit /mnt/etc/systemd/network/eth0.network and add DHCP=yes under [Network]
6. Unmount and exit
7. Select the latest bootscript in the control panel
8. Reboot

**Comment by moul** [comment]
@jezze: thank you for this step-by-step guide ! :+1:

**Comment by moul** [comment]
The new image (released yesterday) contains the fix and the latest version of systemd

**Comment by sneakin** [comment]
Tried this just now and can't login. Even having the "DHCP=yes" line in /etc/systemd/network/eth0.network doesn't allow systemd-resolved and networkd to start. I did manage to logged in with SSH by removing eth0.network, but resolved did not start. Up to systemd-231 now.

**Comment by mikkeloscar** [comment]
@sneakin did you try to add this as well? https://github.com/scaleway/image-archlinux/pull/33/files
