### ISSUE TITLE
sshd won't start after reboot

### ISSUE THREAD

**Issue by lilmike** [scaleway/image-archlinux#30]
Hi,
I just installed all the packages on my server that I'm migrating to (c1, archlinux with all up-to-date packages). When I ssh, it says 'connection refused.' I went into the emergency shell, and did systemctl status -l sshd, and all it said was 'stopped sshd.service' over and over, for each time I tried to systemctl start sshd.service.
Any idea about this? sshdgenkeys.service has the same messages, if that helps.

-Michael.

**Comment by moul** [comment]
Hi @lilmike, 

We will try to investigate, but as we are not ArchLinux experts, I suggest you to ask this question on ArchLinux IRC channel too

**Comment by lilmike** [comment]
Hi,
I figured out why it was, one of my devices (lssd volumes) was not automounting properly, so sshd couldn't start because several dependancies failed. Will open a new ticket for that.
Thanks!\-Michael.
