### ISSUE TITLE
connection timed out on network device nbd0

### ISSUE THREAD

**Issue by lilmike** [scaleway/image-archlinux#32]
Hi,
After a discussion with the support staff, it has been determined that arch linux, the latest packages, has problems with the type of network devices y'all are using. I'm getting lots of errors about connection timed out and unable to read block device when booting my server, causing it not to be able to boot. I'm trying to figure out a work-around for this, as currently I'd rather not switch from arch linux, if only because I have lots of data on that server that I really don't want to have to move.
Any help?
-Michael.

**Comment by lilmike** [comment]
Any news on this? I also have some logs if that would help.
https://pasting.tk/view/af4f9935
-Michael.

**Comment by QuentinPerez** [comment]
Hi @lilmike,

I investigated a little on your issue, and it come from systemd, can you try to upgrade your packages with the following command:

```console
$ pacman -Suy --ignore nbd --ignore libsystemd --ignore systemd --ignore systemd-sysvcompat
```

Let me know if you need anything else 😊

**Comment by roock** [comment]
I'm having issues with the current systemd (version 230) too, although I wasn't able to relate it to the nbd rootfs

**Comment by lilmike** [comment]
Hi,

Is there a work-around for this instead of not upgrading systemd? I've 
already updated systemd, so I'm not quite sure where to go from here.

-Michael.

**Comment by roock** [comment]
In order to prevent further systemd update you can add to `/etc/pacman.conf`: 
`IgnorePkg   = libsystemd systemd systemd-sysvcompat`

You can downgrade systemd with the following command:
```cd /var/cache/pacman/pkg && sudo pacman -U libsystemd-229-3-armv7h.pkg.tar.xz systemd-229-3-armv7h.pkg.tar.xz systemd-sysvcompat-229-3-armv7h.pkg.tar.xz```

**Comment by QuentinPerez** [comment]
Thank you @roock for your help 😊

**Comment by krant** [comment]
Same story here - non-booting Arch on systemd-230-3, downgrade to systemd-229-3 solved the problem.

**Comment by lilmike** [comment]
Hi,
Is it possible that the non-booting, coupled with my attempts to get it booted, would have caused the filesystem to become corrupted? I just booted into rescue mode, and 'mount /dev/nbd0 /mnt/volume1' says 

mount: /dev/nbd0: can't read superblock

dumpe2fs /dev/nbd0 |grep superblock says

Couldn't find valid filesystem superblock.

I can mount my other volume, /dev/nbd1
I'm really starting to get a little worried haha.
-Michael.

**Comment by lilmike** [comment]
Successfully booted.
-Michael.

**Comment by Simnol** [comment]
This is still an issue, and not upgrading the packages isn't really an option.

I raised this with support a few days ago and was told that they couldn't replicate it as an issue, I now know it still is an issue.

**Comment by krant** [comment]
@Simnol do you have this in your /etc/systemd/network/eth0.network:
`[DHCP]`
`CriticalConnection=true`
?

**Comment by Simnol** [comment]
I do now, I opened another issue for it :)

It's been solved, I'm assured that the fix is going to get pushed into the next image.
