### ISSUE TITLE
Upgrading Arch Linux Still Breaks Boot

### ISSUE THREAD

**Issue by Simnol** [scaleway/image-archlinux#34]
Following on from a previous issue, upgrading Arch still results in an unusable OS by default.

The previous suggestion appears to have been to not upgrade systemd packages, which if this is still the case, isn't a fix for the situation. 

Rolling releases occasionally have problems like this, but ignoring them doesn't make them go away.

If there is a solution, it should probably be rolled into the default image, as newcomers (like I was) aren't going to come to the Github issues page as a first port of call.

Support on this issue was very bad.

**Comment by Simnol** [comment]
As I said, if there is a fix already in place for this that I've missed (it's early in the morning) please feel free to close :-)

**Comment by QuentinPerez** [comment]
Hi @Simnol,

If you applied this [fix](https://github.com/scaleway/image-archlinux/commit/b4413928330247c84b6d41ece314682d86739435) you can upgrade systemd

**Comment by Simnol** [comment]
Hi @QuentinPerez,

Thanks, I look forward to the image update. 

Might be worth telling everyone doing support that this issue exists, as the guy I spoke to didn't know ;)

**Comment by ChazyTheBest** [comment]
Hi, I have the same problem, after doing a full system upgrade and restart, it will get stuck and it won't boot anymore:

```
Welcome to Arch Linux ARM!

[ OK ] Listening on Journal Socket (/dev/log).
[ OK ] Listening on udev Control Socket.
[ OK ] Listening on udev Kernel Socket.
[ OK ] Listening on /dev/initctl Compatibility Named Pipe.
[ OK ] Started Forward Password Requests to Wall Directory Watch.
[ OK ] Reached target Remote File Systems.
[ OK ] Listening on LVM2 metadata daemon socket.
[ OK ] Listening on Device-mapper event daemon FIFOs.
[ OK ] Reached target Encrypted Volumes.
[ OK ] Started Dispatch Password Requests to Console Directory Watch.
[ OK ] Reached target Paths.
[ OK ] Created slice System Slice.
[ OK ] Created slice system-serial\x2dgetty.slice.
[ OK ] Reached target Swap.
[ OK ] Created slice User and Session Slice.
[ OK ] Reached target Slices.
[ OK ] Listening on Process Core Dump Socket.
[UNSUPP] Starting of Arbitrary Executable Fi...m Automount Point not supported.
[ OK ] Listening on Journal Socket.
Starting Setup Virtual Console...
Mounting Temporary Directory...
Mounting Debug File System...
Starting Journal Service...
Starting Remount Root and Kernel File Systems...
Mounting POSIX Message Queue File System...
Starting Apply Kernel Variables...
[ OK ] Mounted POSIX Message Queue File System.
[ OK ] Mounted Debug File System.
[ OK ] Mounted Temporary Directory.
[ OK ] Started Setup Virtual Console.
[FAILED] Failed to start Journal Service.
See 'systemctl status systemd-journald.service' for details.
[DEPEND] Dependency failed for Flush Journal to Persistent Storage.
[ OK ] Stopped Journal Service.
Starting Journal Service...
[ OK ] Started Remount Root and Kernel File Systems.
[ OK ] Started Apply Kernel Variables.
Starting Load/Save Random Seed...
Starting Create Static Device Nodes in /dev...
Starting udev Coldplug all Devices...
[FAILED] Failed to start Journal Service.
See 'systemctl status systemd-journald.service' for details.[ OK ] Stopped Journal Service.
Starting Journal Service...
[ OK ] Started Load/Save Random Seed.
[FAILED] Failed to start Journal Service.
See 'systemctl status systemd-journald.service' for details.
[ OK ] Stopped Journal Service.
Starting Journal Service...
[FAILED] Failed to start Create Static Device Nodes in /dev.
See 'systemctl status systemd-tmpfiles-setup-dev.service' for details.
[ OK ] Reached target Local File Systems (Pre).
[ OK ] Reached target Local File Systems.
Starting Create Volatile Files and Directories...
Starting udev Kernel Device Manager...
[FAILED] Failed to start Journal Service.
See 'systemctl status systemd-journald.service' for details.
[ OK ] Stopped Journal Service.
Starting Journal Service...
[FAILED] Failed to start Journal Service.
See 'systemctl status systemd-journald.service' for details.
[ OK ] Stopped Journal Service.
[FAILED] Failed to start Journal Service.
See 'systemctl status systemd-journald.service' for details.
[FAILED] Failed to start Create Volatile Files and Directories.
See 'systemctl status systemd-tmpfiles-setup.service' for details.
Starting Update UTMP about System Boot/Shutdown...
Starting Network Time Synchronization...
[ OK ] Started Update UTMP about System Boot/Shutdown.
[ OK ] Started udev Kernel Device Manager.
[ OK ] Started Network Time Synchronization.
[ OK ] Reached target System Time Synchronized.
[ OK ] Found device /dev/ttyS0.
[ OK ] Started udev Coldplug all Devices.
[ OK ] Reached target System Initialization.
[ OK ] Listening on D-Bus System Message Bus Socket.
[ OK ] Reached target Sockets.
[ OK ] Started Daily rotation of log files.
[ OK ] Started Daily man-db cache purge.
[ OK ] Started Daily Cleanup of Temporary Directories.
[ OK ] Reached target Basic System. Starting SCW generate ssh keys on first boot...
[ OK ] Started Entropy Harvesting Daemon.
[ OK ] Started Daily verification of password and group files.
[ OK ] Reached target Timers.
Starting Network Name Resolution...
[ OK ] Started D-Bus System Message Bus.
Starting Network Service...
Starting Login Service...
Starting SCW fetch kernel modules from Scaleway mirror...
Starting SCW fetch ssh keys from metadata...
[ OK ] Started SCW generate ssh keys on first boot.
[FAILED] Failed to start Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
[ OK ] Started Network Service.
[ OK ] Reached target Network.
Starting One-Shot Network Time Service...
Starting Permit User Sessions...
[ OK ] Stopped Network Name Resolution.
Starting Network Name Resolution...
[FAILED] Failed to start Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
[ OK ] Stopped Network Name Resolution.
Starting Network Name Resolution...
[FAILED] Failed to start Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
[ OK ] Stopped Network Name Resolution.
Starting Network Name Resolution...
[FAILED] Failed to start Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
[ OK ] Stopped Network Name Resolution.
Starting Network Name Resolution...
[FAILED] Failed to start Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
[ OK ] Stopped Network Name Resolution.
[FAILED] Failed to start Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
[FAILED] Failed to start Login Service.
See 'systemctl status systemd-logind.service' for details.
[ OK ] Stopped Login Service.
Starting Login Service...[FAILED] Failed to start Login Service.
See 'systemctl status systemd-logind.service' for details.
[ OK ] Stopped Login Service.
Starting Login Service...
```

**Comment by QuentinPerez** [comment]
Hi @ChazyTheBest, have you tried the [fix](https://github.com/scaleway/image-archlinux/issues/34#issuecomment-229883103) ?

**Comment by ChazyTheBest** [comment]
Not yet, is it just to add those lines to that files before restarting? Because I didn't learn yet how to build one.

**Comment by ChazyTheBest** [comment]
Ok, now it starts but same errors: http://pastebin.com/Tthps6XU

**Comment by QuentinPerez** [comment]
systemd use a new system to generate their `machine-id`, can you do the following command and reboot ?
```console
rm /etc/machine-id
systemd-machine-id-setup
```

**Comment by ChazyTheBest** [comment]
Sure, that almost fixed all of the errors, the one remaining is:

> [FAILED] Failed to start Network Name Resolution.
> See 'systemctl status systemd-resolved.service' for details.
> [  OK  ] Stopped Network Name Resolution.
>          Starting Network Name Resolution...
> [  OK  ] Started Serial Getty on ttyS0.
> [  OK  ] Reached target Login Prompts.
> [  OK  ] Started SCW generate machine id.
>          Starting Hostname Service...
> [FAILED] Failed to start Network Name Resolution.
> See 'systemctl status systemd-resolved.service' for details.
> [  OK  ] Stopped Network Name Resolution.
>          Starting Network Name Resolution...
> [FAILED] Failed to start Network Name Resolution.
> See 'systemctl status systemd-resolved.service' for details.
> [  OK  ] Stopped Network Name Resolution.
>          Starting Network Name Resolution...
> [  OK  ] Started Hostname Service.
> [FAILED] Failed to start Network Name Resolution.
> See 'systemctl status systemd-resolved.service' for details.
> [  OK  ] Stopped Network Name Resolution.
>          Starting Network Name Resolution...
> [  OK  ] Started SCW fetch ssh keys from metadata.
> [FAILED] Failed to start Network Name Resolution.
> See 'systemctl status systemd-resolved.service' for details.
> [  OK  ] Stopped Network Name Resolution.
> [FAILED] Failed to start Network Name Resolution.
> See 'systemctl status systemd-resolved.service' for details.
> [  OK  ] Started One-Shot Network Time Service.

**Comment by ChazyTheBest** [comment]
Not sure, but I think that error is causing apache to always show /srv/http, no matter if I access with one domain or one subdomain, I can navigate (using the navbar) through all the folders within /srv/http... And vhosts is well configured (is the same config from my local computer).

**Comment by ChazyTheBest** [comment]
> # systemctl status systemd-resolved.service
> ● systemd-resolved.service - Network Name Resolution
> Loaded: loaded (/etc/systemd/system/systemd-resolved.service; enabled; vendor preset: enabled)
> Active: failed (Result: start-limit-hit) since Tue 2016-08-02 23:39:01 UTC; 1h 5min ago
> Docs: man:systemd-resolved.service(8)
> Process: 3455 ExecStart=/usr/lib/systemd/systemd-resolved (code=exited, status=1/FAILURE)
> Main PID: 3455 (code=exited, status=1/FAILURE)
> Status: "Shutting down..."
> 
> Aug 02 23:39:01 scw-28a908 systemd[1]: Failed to start Network Name Resolution.
> Aug 02 23:39:01 scw-28a908 systemd[1]: systemd-resolved.service: Unit entered failed state.
> Aug 02 23:39:01 scw-28a908 systemd[1]: systemd-resolved.service: Failed with result 'exit-code'.
> Aug 02 23:39:01 scw-28a908 systemd[1]: systemd-resolved.service: Service has no hold-off time, scheduling restart.
> Aug 02 23:39:01 scw-28a908 systemd[1]: Stopped Network Name Resolution.
> Aug 02 23:39:01 scw-28a908 systemd[1]: systemd-resolved.service: Start request repeated too quickly.
> Aug 02 23:39:01 scw-28a908 systemd[1]: Failed to start Network Name Resolution.
> Aug 02 23:39:01 scw-28a908 systemd[1]: systemd-resolved.service: Unit entered failed state.
> Aug 02 23:39:01 scw-28a908 systemd[1]: systemd-resolved.service: Failed with result 'start-limit-hit'.

Any idea what's wrong?? Thanks.

**Comment by ChazyTheBest** [comment]
@QuentinPerez Please release a new working image.

**Comment by ChazyTheBest** [comment]
@QuentinPerez `system-machine-id-setup` is no longer working in systemd 231...
