### ISSUE TITLE
Failed to start Network Name Resolution (Apache Virtual Hosts not working)

### ISSUE THREAD

**Issue by ChazyTheBest** [scaleway/image-archlinux#36]
(Extending #34 that was closed because the main problem was solved)

After a fresh install and a full system upgrade, the next boot will throw the following error:

> [FAILED] Failed to start Network Name Resolution.
> See 'systemctl status systemd-resolved.service' for details.
> [  OK  ] Stopped Network Name Resolution.
>          Starting Network Name Resolution...
> [  OK  ] Started Serial Getty on ttyS0.
> [  OK  ] Reached target Login Prompts.
> [  OK  ] Started SCW generate machine id.
>          Starting Hostname Service...
> [FAILED] Failed to start Network Name Resolution.
> See 'systemctl status systemd-resolved.service' for details.
> [  OK  ] Stopped Network Name Resolution.
>          Starting Network Name Resolution...
> [FAILED] Failed to start Network Name Resolution.
> See 'systemctl status systemd-resolved.service' for details.
> [  OK  ] Stopped Network Name Resolution.
>          Starting Network Name Resolution...
> [  OK  ] Started Hostname Service.
> [FAILED] Failed to start Network Name Resolution.
> See 'systemctl status systemd-resolved.service' for details.
> [  OK  ] Stopped Network Name Resolution.
>          Starting Network Name Resolution...
> [  OK  ] Started SCW fetch ssh keys from metadata.
> [FAILED] Failed to start Network Name Resolution.
> See 'systemctl status systemd-resolved.service' for details.
> [  OK  ] Stopped Network Name Resolution.
> [FAILED] Failed to start Network Name Resolution.
> See 'systemctl status systemd-resolved.service' for details.
> [  OK  ] Started One-Shot Network Time Service.

This renders apache virtual hosts unusable (always pointing to Main DocumentRoot). I've already made sure it's not a configuration problem.

> \# systemctl status systemd-resolved.service
> ● systemd-resolved.service - Network Name Resolution
>    Loaded: loaded (/etc/systemd/system/systemd-resolved.service; enabled; vendor preset: enabled)
>    Active: failed (Result: start-limit-hit) since Sat 2016-08-06 15:32:19 UTC; 17s ago
>      Docs: man:systemd-resolved.service(8)
>   Process: 4973 ExecStart=/usr/lib/systemd/systemd-resolved (code=exited, status=1/FAILURE)
>  Main PID: 4973 (code=exited, status=1/FAILURE)
>    Status: "Shutting down..."
> 
> Aug 06 15:32:19 scw-28a908 systemd[1]: Failed to start Network Name Resolution.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Unit entered failed state.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Failed with result 'exit-code'.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Service has no hold-off time, scheduling restart.
> Aug 06 15:32:19 scw-28a908 systemd[1]: Stopped Network Name Resolution.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Start request repeated too quickly.
> Aug 06 15:32:19 scw-28a908 systemd[1]: Failed to start Network Name Resolution.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Unit entered failed state.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Failed with result 'start-limit-hit'.

And:

> \# journalctl -xe
> Aug 06 15:32:18 scw-28a908 systemd[1]: Starting Network Name Resolution...
> -- Subject: Unit systemd-resolved.service has begun start-up
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> \-- 
> -- Unit systemd-resolved.service has begun starting up.
> Aug 06 15:32:19 scw-28a908 systemd-resolved[4968]: Failed to increase capabilities: Operation not permitted
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Main process exited, code=exited, status=1/FAILURE
> Aug 06 15:32:19 scw-28a908 systemd[1]: Failed to start Network Name Resolution.
> -- Subject: Unit systemd-resolved.service has failed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> \-- 
> -- Unit systemd-resolved.service has failed.
> \-- 
> -- The result is failed.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Unit entered failed state.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Failed with result 'exit-code'.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Service has no hold-off time, scheduling restart.
> Aug 06 15:32:19 scw-28a908 systemd[1]: Stopped Network Name Resolution.
> -- Subject: Unit systemd-resolved.service has finished shutting down
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> \-- 
> -- Unit systemd-resolved.service has finished shutting down.
> Aug 06 15:32:19 scw-28a908 systemd[1]: Starting Network Name Resolution...
> -- Subject: Unit systemd-resolved.service has begun start-up
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> \-- 
> -- Unit systemd-resolved.service has begun starting up.
> Aug 06 15:32:19 scw-28a908 systemd-resolved[4973]: Failed to increase capabilities: Operation not permitted
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Main process exited, code=exited, status=1/FAILURE
> Aug 06 15:32:19 scw-28a908 systemd[1]: Failed to start Network Name Resolution.
> -- Subject: Unit systemd-resolved.service has failed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> \-- 
> -- Unit systemd-resolved.service has failed.
> \-- 
> -- The result is failed.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Unit entered failed state.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Failed with result 'exit-code'.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Service has no hold-off time, scheduling restart.
> Aug 06 15:32:19 scw-28a908 systemd[1]: Stopped Network Name Resolution.
> -- Subject: Unit systemd-resolved.service has finished shutting down
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> \-- 
> -- Unit systemd-resolved.service has finished shutting down.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Start request repeated too quickly.
> Aug 06 15:32:19 scw-28a908 systemd[1]: Failed to start Network Name Resolution.
> -- Subject: Unit systemd-resolved.service has failed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> \-- 
> -- Unit systemd-resolved.service has failed.
> \-- 
> -- The result is failed.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Unit entered failed state.
> Aug 06 15:32:19 scw-28a908 systemd[1]: systemd-resolved.service: Failed with result 'start-limit-hit'.
> Aug 06 15:35:58 scw-28a908 sshd[4981]: Received disconnect from 121.18.238.22 port 38399:11:  [preauth]
> Aug 06 15:35:58 scw-28a908 sshd[4981]: Disconnected from 121.18.238.22 port 38399 [preauth]
> Aug 06 15:36:56 scw-28a908 sshd[4985]: Received disconnect from 221.194.44.223 port 57688:11:  [preauth]
> Aug 06 15:36:56 scw-28a908 sshd[4985]: Disconnected from 221.194.44.223 port 57688 [preauth]

**Comment by ChazyTheBest** [comment]
Systemd 231 fixes the error on a clean install https://github.com/systemd/systemd/issues/3484

**Comment by ChazyTheBest** [comment]
Not working yet, after resuming the server the errors are back.

The image is outdated and needs to be updated. Hope it can be soon.

**Comment by WarheadsSE** [comment]
Do the latest 4.4.8, 4.5.7 std kernels have SECCOMP enabled?

**Comment by ChazyTheBest** [comment]
The unit file was not updated, so it must be done manually: https://github.com/systemd/systemd/issues/3484#issuecomment-239595447

Now it is really working, well, at least no more errors are shown.

**Comment by WarheadsSE** [comment]
This would not be an issue if a proper systemd unti [drop-in was used](https://coreos.com/os/docs/latest/using-systemd-drop-in-units.html). Overwriting or overriding whole service files is not an intended [vendor behavior. ](https://www.freedesktop.org/software/systemd/man/systemd.preset.html) 

`/etc/systemd/system/systemd-resolved.service.d/start-after-nm-wait-online.conf`

```
[Unit]
After=NetworkManger-wait-online.service
```

**Comment by ChazyTheBest** [comment]
That seems a better approach. Thanks!

**Comment by aspcartman** [comment]
Hm. Commit was merged, but I still meet the error. What do I have to do to survive system update? #41

**Comment by WarheadsSE** [comment]
You will need to manually refactior these files prior to Syu. https://archlinuxarm.org/forum/viewtopic.php?f=60&t=10650&start=10#p52959

**Comment by aspcartman** [comment]
Thx! 
Will this get fixed permanently?

**Comment by QuentinPerez** [comment]
I release a new version of Arch Linux image, can you tell me if you have again this issue ?

**Comment by ChazyTheBest** [comment]
Thanks @QuentinPerez It'll work for sure, waiting for stock to test it.

**Comment by nayanhalder** [comment]
i am facing the same error now in my ubuntu18.04 

[FAILED] Failed to start Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
[ OK ] Stopped Network Name Resolution

Please help me to resolve this issue.

**Comment by YasirNiazai** [comment]
@nayanhalder  have you resolved the issue??
