### ISSUE TITLE
starting order of services is not OK

### ISSUE THREAD

**Issue by aimxhaisse** [scaleway/image-archlinux#4]
On the first boot:

* we don't have resolv.conf
* oc-sync-kernel is called but can't resolv a DNS, fails
* the dhcpd's hook is called, and resolv.conf is set

**Comment by aimxhaisse** [comment]
We are fine on the /etc/resolv.conf now (using systemd's resolver, with a hook in NetworkManager to symlink /etc/resolv.conf to /usr/systemd/...)

**Comment by aimxhaisse** [comment]
Apparently, it's not solved under some circumstances (logs coming).

**Comment by moul** [comment]
Fixed thanks to initrd
